export class Player{
	playerId!: number;
	playerName!: string;
	nickname!: string;
	teamId!: number;
	teamAbbrev!: string;
	age!: number;
	gp!: number;
	won!: number;
	lost!: number;
	wonPct!: number;
	fgm!: number;
	fga!: number;
	fgPct!: number;
	fg3m!: number;
	fg3a!: number;
	fg3Pct!: number;
	ftm!: number;
	fta!: number;
	ftPct!: number;
	oreb!: number;
	dreb!: number;
	reb!: number;
	ast!: number;
	tov!: number;
	stl!: number;
	blk!: number;
	blka!: number;
	pf!: number;
	pts!: number;
  min!: number;
  urlPicture!: string;
  val!: number;
  EFF_PerGame!:number;
  EFF_PerMinute!: number;
  pointsCreated!: number;
  trueShootingPercentage!:number;
  country!: string;
  height!: string;
  weight!: string;
  seasonExp!: number;
  jersey!: string;
  position!: string;
}
